/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author Anthony
 */
public class ViewMain extends javax.swing.JFrame {

    /**
     * Creates new form ViewMain
     */
    public ViewMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jbtn_papelera = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jm_inicio = new javax.swing.JMenu();
        jmi_iniciar = new javax.swing.JMenuItem();
        jmi_usuarios = new javax.swing.JMenuItem();
        jm_catalogo = new javax.swing.JMenu();
        jmi_clientes = new javax.swing.JMenuItem();
        jmi_proveedores = new javax.swing.JMenuItem();
        jmi_productos = new javax.swing.JMenuItem();
        jm_operadores = new javax.swing.JMenu();
        jmi_compras = new javax.swing.JMenuItem();
        jmi_ventas = new javax.swing.JMenuItem();
        jm_reportes = new javax.swing.JMenu();
        jmi_reportes_clientes = new javax.swing.JMenuItem();
        jmi_reportes_proveedores = new javax.swing.JMenuItem();
        jmi_reportes_productos = new javax.swing.JMenuItem();
        jmi_reportes_compras = new javax.swing.JMenuItem();
        jmi_reportes_ventas = new javax.swing.JMenuItem();
        jm_acerca = new javax.swing.JMenu();

        jMenu2.setText("File");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar2.add(jMenu3);

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jbtn_papelera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/recycler_bin_48.png"))); // NOI18N
        jbtn_papelera.setBorder(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(669, Short.MAX_VALUE)
                .addComponent(jbtn_papelera)
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(361, Short.MAX_VALUE)
                .addComponent(jbtn_papelera)
                .addGap(27, 27, 27))
        );

        jm_inicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/home_48.png"))); // NOI18N
        jm_inicio.setText("Inicio");

        jmi_iniciar.setFont(new java.awt.Font("Rod", 0, 18)); // NOI18N
        jmi_iniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/usuario.png"))); // NOI18N
        jmi_iniciar.setText("Iniciar sesion");
        jm_inicio.add(jmi_iniciar);

        jmi_usuarios.setFont(new java.awt.Font("Rod", 0, 18)); // NOI18N
        jmi_usuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/usuarios.png"))); // NOI18N
        jmi_usuarios.setText("Usuarios");
        jm_inicio.add(jmi_usuarios);

        jMenuBar1.add(jm_inicio);

        jm_catalogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/catalogo.png"))); // NOI18N
        jm_catalogo.setText("Catalogo");

        jmi_clientes.setFont(new java.awt.Font("Rod", 0, 18)); // NOI18N
        jmi_clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/clientes.png"))); // NOI18N
        jmi_clientes.setText("Clientes");
        jm_catalogo.add(jmi_clientes);

        jmi_proveedores.setFont(new java.awt.Font("Rod", 0, 18)); // NOI18N
        jmi_proveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/proveedores.png"))); // NOI18N
        jmi_proveedores.setText("Proveedores");
        jm_catalogo.add(jmi_proveedores);

        jmi_productos.setFont(new java.awt.Font("Rod", 0, 18)); // NOI18N
        jmi_productos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/productos.png"))); // NOI18N
        jmi_productos.setText("Productos");
        jm_catalogo.add(jmi_productos);

        jMenuBar1.add(jm_catalogo);

        jm_operadores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/empty_shopping_cart_32.png"))); // NOI18N
        jm_operadores.setText("Operadores");

        jmi_compras.setFont(new java.awt.Font("Rod", 0, 18)); // NOI18N
        jmi_compras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/compras.png"))); // NOI18N
        jmi_compras.setText("Compras");
        jm_operadores.add(jmi_compras);

        jmi_ventas.setFont(new java.awt.Font("Rod", 0, 18)); // NOI18N
        jmi_ventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/ventas.png"))); // NOI18N
        jmi_ventas.setText("Ventas");
        jm_operadores.add(jmi_ventas);

        jMenuBar1.add(jm_operadores);

        jm_reportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/reportes.png"))); // NOI18N
        jm_reportes.setText("Reportes");

        jmi_reportes_clientes.setFont(new java.awt.Font("Rod", 0, 18)); // NOI18N
        jmi_reportes_clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/clientes.png"))); // NOI18N
        jmi_reportes_clientes.setText("Clientes");
        jm_reportes.add(jmi_reportes_clientes);

        jmi_reportes_proveedores.setFont(new java.awt.Font("Rod", 0, 18)); // NOI18N
        jmi_reportes_proveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/proveedores.png"))); // NOI18N
        jmi_reportes_proveedores.setText("Proveedores");
        jmi_reportes_proveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_reportes_proveedoresActionPerformed(evt);
            }
        });
        jm_reportes.add(jmi_reportes_proveedores);

        jmi_reportes_productos.setFont(new java.awt.Font("Rod", 0, 18)); // NOI18N
        jmi_reportes_productos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/productos.png"))); // NOI18N
        jmi_reportes_productos.setText("Productos");
        jm_reportes.add(jmi_reportes_productos);

        jmi_reportes_compras.setFont(new java.awt.Font("Rod", 0, 18)); // NOI18N
        jmi_reportes_compras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/compras.png"))); // NOI18N
        jmi_reportes_compras.setText("Compras");
        jm_reportes.add(jmi_reportes_compras);

        jmi_reportes_ventas.setFont(new java.awt.Font("Rod", 0, 18)); // NOI18N
        jmi_reportes_ventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/ventas.png"))); // NOI18N
        jmi_reportes_ventas.setText("Ventas");
        jm_reportes.add(jmi_reportes_ventas);

        jMenuBar1.add(jm_reportes);

        jm_acerca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/acerda de.png"))); // NOI18N
        jm_acerca.setText("Acerca de");
        jMenuBar1.add(jm_acerca);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmi_reportes_proveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_reportes_proveedoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmi_reportes_proveedoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem4;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JButton jbtn_papelera;
    public javax.swing.JMenu jm_acerca;
    public javax.swing.JMenu jm_catalogo;
    public javax.swing.JMenu jm_inicio;
    public javax.swing.JMenu jm_operadores;
    public javax.swing.JMenu jm_reportes;
    public javax.swing.JMenuItem jmi_clientes;
    public javax.swing.JMenuItem jmi_compras;
    public javax.swing.JMenuItem jmi_iniciar;
    public javax.swing.JMenuItem jmi_productos;
    public javax.swing.JMenuItem jmi_proveedores;
    public javax.swing.JMenuItem jmi_reportes_clientes;
    public javax.swing.JMenuItem jmi_reportes_compras;
    public javax.swing.JMenuItem jmi_reportes_productos;
    public javax.swing.JMenuItem jmi_reportes_proveedores;
    public javax.swing.JMenuItem jmi_reportes_ventas;
    public javax.swing.JMenuItem jmi_usuarios;
    public javax.swing.JMenuItem jmi_ventas;
    // End of variables declaration//GEN-END:variables
}
